version: '3.5'

services:
  cups:
    container_name: cups
    image: pokica/cups-avahi-airprint
    #build: .
    restart: always
    network_mode: "host"
    environment:
      CUPSADMIN: cups       # replace it with your desired username
      CUPSPASSWORD: cups    # replace it with your desired password
    volumes:
      - ./services:/services
      - ./config:/config
      - ./logs:/var/logs/cups
      - /var/run/dbus:/var/run/dbus
    devices:
      - /dev/bus:/dev/bus
