version: '3.5'

services:
  cups:
    container_name: cups
    image: pokica/cups-avahi-airprint
    #build: .
    restart: always
    network_mode: "host"
    environment:
      CUPSADMIN: cups
      CUPSPASSWORD: cups
    volumes:
      - "./services:/services"
      - "./config:/config"
